sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 1
  wechat:
    appid: wx97ada8edbfcbabe5
    secret: 3b5e29035c16e47248e9a9c2f53d9fc5
    mchid: xxxxxxxxx
    mchSerialNo: xxxxxxxxxxx
    privateKeyFilePath: xxxxxxxxxxx
    apiV3Key: xxxxxxxxxx
    weChatPayCertFilePath: xxxxxxxxxxxx
    notifyUrl: xxxxxxxxxxx
    refundNotifyUrl: xxxxxxxxxxxxx
